version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - dockernode
  dockernode:
    build: .
    image: skouky/dockernode
    environment:
      - PORT=2999
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - data/mongodb:/data/db
      - data/mongodbbackups:/data/db/backups

  redis:
    image: redis
