version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - dockernode
  dockernode:
    build: .
    environment:
      - PORT=2999
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
