version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.certbot.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbotdir/var/www/certbot:/var/www/certbot
