version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - dockernode
  dockernode:
    build: .
    image: skouky/dockernode
    environment:
      - PORT=2999
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
      - ./data/mongodbbackups:/data/db/backups
      - ./mongoinit/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  redis:
    image: redis
